### ISSUE TITLE
Couldn't find class DaggerActivityComponent

### ISSUE THREAD

**Issue by anas-incedo** [hitherejoe/AndroidTvBoilerplate#3]
`DaggerActivityComponent ` is referenced in many classes, but it doesn't exist in the `com.hitherejoe.androidtvboilerplate.injection.component` package.

I think it is self-explanatory. Please tell me how to fix this.

**Comment by nitin-android** [comment]
i am also searching. id you found any answer please let me know.

**Comment by nitin-android** [comment]
@anas-incedo  i have just changed the Android Studio ver 3.0 to ver 2.3.2.

**Comment by anas-incedo** [comment]
Thanks, @nitin-android, it helped.
